// Next Imports
import Head from 'next/head'

// Components
import Header from '../components/Header'
import ServiceDetails from '../components/ServiceDetails'

// Context
import { GlobalProvider } from '../context/GlobalState'

const GlobalLayout = ({children}) => {
    return (
        <GlobalProvider>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main>{children}</main>

            <ServiceDetails />
        </GlobalProvider>
    )
}

export default GlobalLayout